In [1]:
from functions import *
import numpy as np
import os
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from math import *

In [2]:
def DatesInRange(start,end):
    from datetime import datetime, timedelta
    import os
    import numpy as np
    NMRFolders=os.listdir('NMRData')
    foldersRefined=np.empty(0)
    inRange=np.empty(0)
    inRangeIndex=np.empty(0)
    for i in range(0,len(NMRFolders)):
        
        elements=NMRFolders[i].split('_')
        combined=elements[2]+'_'+elements[3]
        foldersRefined=np.append(foldersRefined,combined)
    start_date = datetime.strptime(start, "%Y%m%d_%H%M%S")
    end_date = datetime.strptime(end, "%Y%m%d_%H%M%S")
    for i in range(0,len(foldersRefined)):
        date = datetime.strptime(foldersRefined[i], "%Y%m%d_%H%M%S")
        if start_date <= date <= end_date:
            inRangeIndex=np.append(inRangeIndex,i)
            inRange=np.append(inRange,foldersRefined[i])
    return inRangeIndex.astype(int),inRange
    
def GrabSweepAtIndex(j):
    import os
    import numpy as np
    NMRFolders=os.listdir('NMRData')

    dates=np.empty(0)
    allSweeps=np.empty((0,0,0))

    downstreamFolder=os.listdir('NMRData/'+NMRFolders[j]+'/Downstream Coil')
    upstreamFolder=os.listdir('NMRData/'+NMRFolders[j]+'/Upstream Coil')
    pumpingchamberFolder=os.listdir('NMRData/'+NMRFolders[j]+'/Pumping Chamber')


    
    for i, s in enumerate(downstreamFolder):
        if s.startswith('0001') and s.endswith('.dat'):
            DSindex = i
            break

    for i, s in enumerate(upstreamFolder):
        if s.startswith('0001') and s.endswith('.dat'):
            USindex = i
            break

    for i, s in enumerate(pumpingchamberFolder):
        if s.startswith('0001') and s.endswith('.dat'):
            PCindex = i
            break

    singleDSData=np.expand_dims(np.transpose(np.loadtxt('NMRData/'+NMRFolders[j]+'/Downstream Coil/'+downstreamFolder[DSindex])),axis=0)
    singleUSData=np.expand_dims(np.transpose(np.loadtxt('NMRData/'+NMRFolders[j]+'/Upstream Coil/'+upstreamFolder[USindex])),axis=0)
    singlePCData=np.expand_dims(np.transpose(np.loadtxt('NMRData/'+NMRFolders[j]+'/Pumping Chamber/'+pumpingchamberFolder[PCindex])),axis=0)
    dates=np.append(dates,NMRFolders[j])

    oneSweep=np.concatenate((singleDSData,singleUSData,singlePCData),axis=0)
    #the first index of oneSweep is the downstream data, second is the upstream data, third is the pumping chamber data
    return oneSweep


In [3]:
def Search(x,value):
    end=abs(x[-1:]-x[0])
    valueNorm=abs(value-x[0])
    ratio=valueNorm/end
    index=int(ratio*(len(x)-1))
    print(x[index])  
        

In [4]:

def GrabClosest(date,data):
    from datetime import datetime, timedelta
    import os
    import numpy as np
    goUp=False
    goDown=False
    found=False
   
    #get an initial index guess
    end=datetime.strptime(data[0][-1:][0],"%Y%m%d_%H%M%S")-datetime.strptime(data[0][0],"%Y%m%d_%H%M%S")
   
    
    valueNorm=datetime.strptime(date,"%Y%m%d_%H%M%S")-datetime.strptime(data[0][0],"%Y%m%d_%H%M%S")
  
    ratio=valueNorm.total_seconds()/end.total_seconds()

    index=int(ratio*(len(data[0])-1))
    
    
    while found==False:
        baseline=abs(datetime.strptime(date,"%Y%m%d_%H%M%S")-datetime.strptime(data[0][index],"%Y%m%d_%H%M%S")).total_seconds()
        below=abs(datetime.strptime(date,"%Y%m%d_%H%M%S")-datetime.strptime(data[0][index-1],"%Y%m%d_%H%M%S")).total_seconds()
        above=abs(datetime.strptime(date,"%Y%m%d_%H%M%S")-datetime.strptime(data[0][index+1],"%Y%m%d_%H%M%S")).total_seconds()
        
        goDown=False
        goUp=False
        if below<baseline:
            goDown=True
            index=index-1
            
        if above<baseline:
            goUp=True
            index=index+1
            
        if goDown ==False and goUp==False:
            found=True
    
    ydat=data[1].astype(float)
   
    return(ydat[index])  

In [5]:
tempData=LoadEpics()
tc1,tc2,tc3,tc4,pc1,pc2,tt1,tt2=tempData

Format: tc1,tc2,tc3,tc4,pc1,pc2,tt1,tt2


In [247]:
date="20221101_050000"

In [249]:
%%time
GrabClosest(date,tempData[1])

CPU times: user 399 ms, sys: 147 µs, total: 399 ms
Wall time: 398 ms


33.276400566101074

In [213]:
%%time
GrabClosest(date,tempData[1])

76 days, 0:00:00
31
90548 20221104_230651
baseline:  342411.0
GoingDown
baseline:  342381.0
GoingDown
baseline:  342368.0
GoingDown
baseline:  342360.0
GoingDown
baseline:  342279.0
GoingDown
baseline:  342277.0
GoingDown
baseline:  342229.0
GoingDown
baseline:  342219.0
GoingDown
baseline:  342209.0
GoingDown
baseline:  342137.0
GoingDown
baseline:  342132.0
GoingDown
baseline:  342068.0
GoingDown
baseline:  342066.0
GoingDown
baseline:  342019.0
GoingDown
baseline:  342013.0
GoingDown
baseline:  341928.0
GoingDown
baseline:  341927.0
GoingDown
baseline:  341862.0
GoingDown
baseline:  341853.0
GoingDown
baseline:  341849.0
GoingDown
baseline:  341848.0
GoingDown
baseline:  341769.0
GoingDown
baseline:  341744.0
GoingDown
baseline:  341685.0
GoingDown
baseline:  341683.0
GoingDown
baseline:  341640.0
GoingDown
baseline:  341639.0
GoingDown
baseline:  341557.0
GoingDown
baseline:  341552.0
GoingDown
baseline:  341494.0
GoingDown
baseline:  341491.0
GoingDown
baseline:  341464.0
GoingDow

baseline:  166933.0
GoingDown
baseline:  166903.0
GoingDown
baseline:  166850.0
GoingDown
baseline:  166845.0
GoingDown
baseline:  166811.0
GoingDown
baseline:  166773.0
GoingDown
baseline:  166745.0
GoingDown
baseline:  166714.0
GoingDown
baseline:  166658.0
GoingDown
baseline:  166657.0
GoingDown
baseline:  166633.0
GoingDown
baseline:  166630.0
GoingDown
baseline:  166601.0
GoingDown
baseline:  166466.0
GoingDown
baseline:  166428.0
GoingDown
baseline:  166421.0
GoingDown
baseline:  166417.0
GoingDown
baseline:  166366.0
GoingDown
baseline:  166363.0
GoingDown
baseline:  166324.0
GoingDown
baseline:  166261.0
GoingDown
baseline:  166259.0
GoingDown
baseline:  166230.0
GoingDown
baseline:  166183.0
GoingDown
baseline:  166165.0
GoingDown
baseline:  166140.0
GoingDown
baseline:  166097.0
GoingDown
baseline:  166087.0
GoingDown
baseline:  166084.0
GoingDown
baseline:  165939.0
GoingDown
baseline:  165930.0
GoingDown
baseline:  165929.0
GoingDown
baseline:  165863.0
GoingDown
baseline: 

baseline:  104345.0
GoingDown
baseline:  104341.0
GoingDown
baseline:  104333.0
GoingDown
baseline:  104255.0
GoingDown
baseline:  104238.0
GoingDown
baseline:  104235.0
GoingDown
baseline:  104188.0
GoingDown
baseline:  104186.0
GoingDown
baseline:  104163.0
GoingDown
baseline:  104151.0
GoingDown
baseline:  104148.0
GoingDown
baseline:  104023.0
GoingDown
baseline:  104016.0
GoingDown
baseline:  104015.0
GoingDown
baseline:  103980.0
GoingDown
baseline:  103978.0
GoingDown
baseline:  103942.0
GoingDown
baseline:  103900.0
GoingDown
baseline:  103893.0
GoingDown
baseline:  103888.0
GoingDown
baseline:  103841.0
GoingDown
baseline:  103827.0
GoingDown
baseline:  103814.0
GoingDown
baseline:  103808.0
GoingDown
baseline:  103728.0
GoingDown
baseline:  103715.0
GoingDown
baseline:  103667.0
GoingDown
baseline:  103664.0
GoingDown
baseline:  103617.0
GoingDown
baseline:  103611.0
GoingDown
baseline:  103562.0
GoingDown
baseline:  103561.0
GoingDown
baseline:  103515.0
GoingDown
baseline: 

CPU times: user 648 ms, sys: 7.9 ms, total: 656 ms
Wall time: 653 ms


28.73255729675293

In [129]:
x

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9,
       12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. ,
       13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1,
       14.2, 14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2,
       15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16

In [59]:
x=np.arange(1,20,.1)
BinarySearch(x,7)

6.900000000000006


In [9]:
len(x)

40

In [28]:
indicesInRange,datesInRange = DatesInRange('20221108_000000','20221122_60000')

In [29]:
NMRFolders=os.listdir('NMRData')

In [30]:
indicesInRange

array([  0,   3,   6,   7,   8,   9,  11,  14,  20,  21,  23,  26,  42,
        53,  57,  59,  60,  61,  75,  93, 103, 104, 107, 108, 109, 111,
       125, 133, 146, 147, 153, 154, 161, 164, 165, 166, 169, 171, 173,
       175, 179, 189, 193, 202, 207, 209, 211, 213, 214, 215, 218, 219,
       221, 228, 229, 231, 236, 240, 246, 247, 249, 252, 259, 264, 265,
       268, 270, 277, 278, 281, 287, 294, 310, 318, 322, 324, 326, 332,
       335, 341, 345, 346, 347, 354, 356, 358, 361, 363, 364, 365, 366,
       369, 380, 382, 383, 388, 396, 399, 414, 426, 431, 432, 434, 437,
       443, 462, 467, 473, 478, 481, 487, 496, 500, 507, 517, 519, 522,
       523, 527, 530, 540, 544, 545, 548, 551, 557, 559, 562, 569, 574,
       578, 579, 587, 592, 601, 610, 614, 622, 630, 631, 636, 640, 642,
       645, 648, 651, 654])

In [31]:
oneSweep=GrabSweepAtIndex(indicesInRange[128])

In [32]:
oneSweep

array([[[ 2.3511999e+01,  2.3551134e+01,  2.3590267e+01, ...,
          3.3882599e+01,  3.3921730e+01,  3.3960865e+01],
        [-1.6794000e-02, -2.3499000e-02, -2.6867000e-02, ...,
          5.8746300e-01,  5.9081600e-01,  5.9081600e-01],
        [-3.0884100e-01, -3.2898800e-01, -3.5248700e-01, ...,
          5.9081600e-01,  5.9081600e-01,  5.9081600e-01],
        [ 0.0000000e+00,  0.0000000e+00,  3.3530000e-03, ...,
         -1.9806600e-01, -1.9806600e-01, -2.0141900e-01],
        [ 1.0058000e-02,  2.0131000e-02,  2.6852000e-02, ...,
         -1.9471300e-01, -1.9806600e-01, -2.0141900e-01]],

       [[ 2.3511999e+01,  2.3551134e+01,  2.3590267e+01, ...,
          3.3882599e+01,  3.3921730e+01,  3.3960865e+01],
        [ 3.0205000e-02,  3.3557000e-02,  4.0278000e-02, ...,
         -5.3376000e-01, -5.3711200e-01, -5.3711200e-01],
        [ 2.2827100e-01,  2.4169700e-01,  2.5847600e-01, ...,
         -5.4048000e-01, -5.3711200e-01, -5.3711200e-01],
        [ 2.3484000e-02,  2.0131000e-0